### ISSUE TITLE
Schematic

### ISSUE THREAD

**Issue by tamasharasztosi** [Xinyuan-LilyGO/LilyGo-esp32s2-base#3]
Can you upload the schematic for "TTGO T8 ESP32-S2 V1.1" (with card slot)?

**Comment by aleggon** [comment]
They don't care. Let's go buy boards from Europe and America.

**Comment by tamasharasztosi** [comment]
![Képkivágás](https://user-images.githubusercontent.com/25348566/101335486-8ea04b00-3879-11eb-816f-1f3db5f98555.JPG)

**Comment by aleggon** [comment]
This is not a schematic. It's a pinout.

**Comment by tamasharasztosi** [comment]
> This is not a schematic. It's a pinout.

You can be sure I am pretty much aware of that.
facepalm

**Comment by lewisxhe** [comment]
The schematic has been uploaded.
